% Reproducibility script for Example 1 of the paper:
% "Small-Data Modeling of Electromagnetic Structures via
% Compressed Vector-Valued Kernel Ridge Regression"
%
% This script reproduces the VV-KRR results for the high-speed-link
% benchmark (Example 1), including:
% 1) the VV-KRR entry corresponding to model #4 in Table 4,
% 2) the scatter plot in Fig. 5,
% 3) the parametric plot in Fig. 6.
%
% By changing the input kernel kx and the output kernel ko,
% it is also possible to reproduce the other VV-KRR configurations
% reported in Table 4 of the paper.

clear all;
clc;
close all;

% Add the VV-KRR toolbox folder and all its subfolders.
% The folder "tool_VVKRR_v0" is assumed to be located in the same
% directory as this main script.
addpath(genpath('../../tool_VVKRR_v0'));


% Plot/font settings used in the figures
FS = 15;
FN = 'Times';
FW = 'normal';
FA = 'normal';


%% Load dataset for Example 2

% X_ED_norm and Y_ED collect the training input and output samples
%
% X_TEST_norm and Y_TEST collect the test input and ouput samples

% % The input samples are generated by Latin hypercube sampling in the
% % normalized domain [-1,1]^11 and then mapped to the corresponding
% % physical parameters of the structure.
% %
% % The output responses are computed by evaluating the transfer function
% % at 100 frequency points between 1 MHz and 5 GHz. The frequency points
% are collected in the vector freq.

load("Example02_dataset.mat")



N_MC = size(S21_mc,2);

Npadding = 10;

for ii=1:N_MC
    
    XX = [real(S11_mc(:,ii));zeros(Npadding,1);imag(S11_mc(:,ii));zeros(Npadding,1); real(S21_mc(:,ii));zeros(Npadding,1);imag(S21_mc(:,ii))];
    Y_ZP(ii,:) = XX.';
        
end


N_freq = size(freq,1);

% check
figure
plot(freq,Y_ZP(1:5:100,1:N_freq),'b')


%% Defining test and training samples

N_ED = 400; 

index = 1:N_MC;

X_ED = x_mc(index(1:N_ED),:);
Y_ED = Y_ZP(index(1:N_ED),:);

X_TEST = x_mc(index(500+1:end),:);
Y_TEST = Y_ZP(index(500+1:end),:);

Y_gold_S11_TEST = S11_mc(:,index(500+1:end)).';
Y_gold_S21_TEST = S21_mc(:,index(500+1:end)).';

N_TEST = size(Y_TEST,1);

%% MC plot
figure
subplot(2,1,1)
plot(freq,abs(S11_mc))

% title sub 1
title('S11: MC example 2 computed on the test set')
% Axis labels
xlabel('Frequency (GHz)', 'FontSize', FS, 'FontName', FN);
ylabel('S11 (linear)', 'FontSize', FS, 'FontName', FN);


subplot(2,1,2)
plot(freq,abs(S21_mc))

% title sub 1
title('S21: MC example 2 computed on the test set')

% Axis labels
xlabel('Frequency (GHz)', 'FontSize', FS, 'FontName', FN);
ylabel('S21 (linear)', 'FontSize', FS, 'FontName', FN);

% Main plot aesthetics
axis tight;
grid on;
box on;
set(gcf, 'Color', 'w');

%% Modeling

% Compression / truncation tolerance used in the VV-KRR training
tol = 1e-6;

% Build the output kernel matrix from the empirical correlation
% of the training outputs
B = corr(Y_ED);

% Replace NaN entries, which may appear if some output components
% have zero variance in the training set
index_B = find(isnan(B));
B(index_B) = 0;

% Enforce symmetry of the output kernel matrix
B = 0.5*(B+B.');

% Start training timer
t1 = tic;

% Train the VV-KRR model.
%
% X_ED_norm : normalized training inputs
% Y_ED      : training outputs
% kx        : input kernel type
% ko        : output kernel matrix or analytic output kernel type
% []        : optional extra arguments not used here
% 5         : number of CV folds
% tol       : compression tolerance
%
% By changing kx and ko, it is possible to reproduce the VV-KRR
% results reported in Table 3 of the paper.
kx = 'ardMatern52';   % or 'Matern52'; 'RBF'; 'ardRBF'; 'Matern12'; 'ardMatern12'
ko = B;               % or 'Matern52'; 'RBF'; 'Matern12'

MODEL = train_VVRR_CV_learn_v20(X_ED,Y_ED,kx,ko,[],5,tol,'s','L2');


% Stop training timer
time_training = toc(t1);

% Start prediction timer
t2 = tic;

% Predict outputs on the test set
Y_pred_tmp = predict_VVRR_model_v7(MODEL,X_TEST,[]);

% Stop prediction timer
time_prediction = toc(t2);


% Building complex valued from zero-padding
Y_pred_S11 = Y_pred_tmp(:,1:N_freq)+1j*Y_pred_tmp(:,(N_freq+1+Npadding):(2*N_freq+Npadding));
Y_pred_S21 = Y_pred_tmp(:,(2*N_freq+1+2*Npadding):(3*N_freq+2*Npadding))+1j*Y_pred_tmp(:,(3*N_freq+1+3*Npadding):end);

Y_pred = [Y_pred_S11;Y_pred_S21];
Y_TEST = [Y_gold_S11_TEST;Y_gold_S21_TEST];

%%%% computing error

eps_norm = 1e-12;

% L2 rel
L2_rel_Error = norm((Y_TEST - Y_pred), 'fro') / (norm(Y_TEST, 'fro') + eps_norm)*100

%Linf rel
Linf_rel_Error = norm(abs(Y_TEST(:)-Y_pred(:)),inf)/norm(abs(Y_TEST(:)),inf)*100

%% Display summary in Command Window
fprintf('\n\n---------------------\n');
fprintf('--- VV-KRR MODEL SUMMARY ---\n');

% Number of training samples
fprintf('Number of training samples: %d\n', size(X_ED,1));

% Input and output kernel types actually stored in the trained model
fprintf('Input kernel kx: %s\n', MODEL.kx_kernel.type);
fprintf('Output kernel ko: %s\n', MODEL.ko_kernel.type);

% Compression tolerance
fprintf('Tolerance: %.1e\n', MODEL.tol);

% Compression summary
fprintf('Retained input modes nx: %d\n', MODEL.nx);
fprintf('Retained output modes no: %d\n', MODEL.no);
fprintf('Number of retained coefficients: %d\n', MODEL.nx * MODEL.no);

% Timing information
fprintf('Training time: %.4f seconds\n', time_training);
fprintf('Prediction time: %.4f seconds\n', time_prediction);

% Error metrics
fprintf('L2 relative error: %.1f\n', L2_rel_Error);
fprintf('Linf relative error: %.1f\n', Linf_rel_Error);

%% single scatter
figure

% ---- Subplot 1: Real Part ----
subplot(1, 2, 1)
hold on
set(gca, 'FontSize', FS, 'LineWidth', 1.2)

scatter(real(Y_gold_S11_TEST(:)), real(Y_pred_S11(:)), 30, 'm', 'x', 'LineWidth', 1.2)

min_val_real = min([real(Y_gold_S11_TEST(:)); real(Y_pred_S11(:))]);
max_val_real = max([real(Y_gold_S11_TEST(:)); real(Y_pred_S11(:))]);
plot([min_val_real, max_val_real], [min_val_real, max_val_real], 'k--', 'LineWidth', 1.2)

xlabel('Actual Values', 'FontSize', FS)
ylabel('Model Prediction', 'FontSize', FS)
title('Re\{S_{11}\}', 'FontSize', FS)
legend('Model #4', 'FontSize', FS, 'Location', 'southeast', 'FontName', 'Arial')

axis square
axis tight
grid on
box on

% ---- Subplot 2: Imaginary Part ----
subplot(1, 2, 2)
hold on
set(gca, 'FontSize', FS, 'LineWidth', 1.2)

scatter(imag(Y_gold_S11_TEST(:)), imag(Y_pred_S11(:)), 30, 'm', 'x', 'LineWidth', 1.2)

min_val_imag = min([imag(Y_gold_S11_TEST(:)); imag(Y_pred_S11(:))]);
max_val_imag = max([imag(Y_gold_S11_TEST(:)); imag(Y_pred_S11(:))]);
plot([min_val_imag, max_val_imag], [min_val_imag, max_val_imag], 'k--', 'LineWidth', 1.2)

xlabel('Actual Values', 'FontSize', FS)
ylabel('Model Prediction', 'FontSize', FS)
title('Im\{S_{11}\}', 'FontSize', FS)

axis square
axis tight
grid on
box on

% ---- Global settings ----
set(gcf, 'Color', 'w')

% Optional: export
exportgraphics(gcf, 'scatter_ex2_S11_real_imag_combined.eps', ...
    'ContentType', 'vector', 'BackgroundColor', 'none')

%% parametric Real

figure
hold on
set(gca, 'FontSize', FS, 'LineWidth', 1.2)

% Plot reference and model predictions
plot(freq/1e9, real(Y_gold_S11_TEST(1,:)), 'k-', 'LineWidth', 2.5)
plot(freq/1e9, real(Y_pred_S11(1,:)), 'm--', 'LineWidth', 2)


plot(freq/1e9, real(Y_gold_S11_TEST(1:6:30,:)), 'k-', 'LineWidth', 2.5)
plot(freq/1e9, real(Y_pred_S11(1:6:30,:)), 'm--', 'LineWidth', 2)

% Axis labels
%xlabel('Frequency (GHz)', 'FontSize', FS)
ylabel('Re\{S11\}', 'FontSize', FS)

% Legend
legend({'Reference', 'Model #4'}, 'FontSize', FS, 'Location', 'southeast', 'FontName', 'Arial')


% Main plot aesthetics
axis tight
grid on
box on
set(gcf, 'Color', 'w')
pbaspect([2 1.2 1])

%exportgraphics(gcf, 'param_ex2_S11_real.eps', 'ContentType', 'vector', 'BackgroundColor', 'none')





%% imag
figure
hold on
set(gca, 'FontSize', FS, 'LineWidth', 1.2)

% Plot reference and model predictions
plot(freq/1e9, imag(Y_gold_S11_TEST(1,:)), 'k-', 'LineWidth', 2.5)
plot(freq/1e9, imag(Y_pred_S11(1,:)), 'm--', 'LineWidth', 2)

plot(freq/1e9, imag(Y_gold_S11_TEST(1:6:30,:)), 'k-', 'LineWidth', 2.5)
plot(freq/1e9, imag(Y_pred_S11(1:6:30,:)), 'm--', 'LineWidth', 2)

% Axis labels
xlabel('Frequency (GHz)', 'FontSize', FS)
ylabel('Im\{S11\}', 'FontSize', FS)

% Main plot aesthetics
axis tight
grid on
box on
set(gcf, 'Color', 'w')
pbaspect([2 1.2 1])

%% plot ko
D_OUT_TEST = [];

if strcmp(MODEL.ko_kernel.type, 'GIVEN')

    B_TEST = MODEL.ko_kernel.B;%(1-MODEL.params.ko_sigma_l)*MODEL.ko_kernel.B+eye(size(MODEL.ko_kernel.B))*MODEL.params.ko_sigma_l;%MODEL.ko_kernel.B;
else

    if isempty(D_OUT_TEST)
        D_OUT_TEST = MODEL.D_OUT_ED;
    end

    D_OUT_ED = MODEL.D_OUT_ED;

    switch MODEL.ko_kernel.type

        case 'RBF' 
            sigma_f = 1;
            B_TEST = kernel_sqexp(D_OUT_ED,D_OUT_TEST,sigma_f,MODEL.params.ko_sigma_l);

        case 'Matern52'
            sigma_f = 1;
            B_TEST = kernel_matern52(D_OUT_ED,D_OUT_TEST,sigma_f,MODEL.params.ko_sigma_l);

        case 'Matern12'
            sigma_f = 1;
            B_TEST = kernel_matern12(D_OUT_ED,D_OUT_TEST,sigma_f,MODEL.params.ko_sigma_l);
    end

end

% --------------------------
% Inset plot (B Matrix)
% --------------------------
%inset_pos = [0.60, 0.60, 0.30, 0.30];  % [x, y, width, height] in normalized units

inset_pos = [0.29, 0.25, 0.30, 0.30];  % [x, y, width, height] in normalized units
inset_axes = axes('Position', inset_pos);

imagesc(freq/1e9, freq/1e9, B_TEST)
set(inset_axes, 'FontSize', FS-2, 'LineWidth', 1)
colormap(inset_axes, parula)
axis square tight
box on

xlabel('','FontSize', FS-2)
ylabel('','FontSize', FS-2)
title('B Matrix', 'FontSize', FS-2)

% Optional: turn off x/y ticks in the inset to keep it clean
set(inset_axes, 'XTick', [], 'YTick', [])

% Add colorbar if you want (small)
colorbar('Position', [0.56, 0.25, 0.01, 0.30]);

% Export to EPS
%print('param_ex2_S11_imag.eps', '-depsc');
%exportgraphics(gcf, 'param_ex2_S11_imag.eps', 'ContentType', 'vector', 'BackgroundColor', 'none')



